from pydantic import BaseModel, Field

class RagQueryRequest(BaseModel):
    question: str = Field(
        min_length=3,
        max_length=500,
        description="The question to be answered by the RAG system."
    )

class RagQueryResponse(BaseModel):
    status: str = Field(
        description="The status of the RAG query, e.g., 'success' or 'error'."
    )
    answer: str = Field(
        description="The answer generated by the RAG system based on the retrieved documents."
    )